project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "CV Notes"
        contents:
          - chess_board_segmentation.qmd
          - chess_board_segmentation_with_flat_board.qmd
      - section: "Utilities"
        contents:
          - utilities/video_to_images.qmd
          - utilities/segmenting_by_color.qmd

          

format:
  html:
    theme: flatly
    toc: true
    fontsize: 1.1em
    linestretch: 1.7