project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Research Notebooks"
        contents:
          - chess_board_segmentation.qmd
      - section: "Utilities"
        contents:
          - utilities/video_to_images.qmd

          

format:
  html:
    theme: cosmo
    toc: true